$color = rgba(245, 242, 233, 1)
$inner_color = rgba(245, 242, 233, 0.66)
$outer_color = rgba(121, 110, 81, 1)
$font_color = rgba(73, 41, 36, 1)
$placeholder_color = rgba(73, 41, 36, 0.7)
$check_color = rgba(114, 105, 71, 1)
